H2 Test Database + Postgres Database integration
LeNelSoN/teamoop-backend pull request #19
Opened 2024-12-24 16:10 UTC by allanserre

2024-12-26 15:38 UTC, LeNelSoN commented
Il faut séparer les responsabilités. La PR concerne soit les test H2, soit l'intégration de Postgresql.

2024-12-26 15:48 UTC, LeNelSoN commented
Et faudrait refaire une PR avec l'ajout de la feature project.

2024-12-26 15:48 UTC, LeNelSoN commented on docker-compose.yml
> +    driver: local
C’est correct mais c’est pas utile de le préciser, c’est local par défaut.

2024-12-26 15:48 UTC, LeNelSoN commented on src/main/java/com/edj/teamoop/config/SecurityConfig.java
> +    public SecurityFilterChain securityFilterChainProd(HttpSecurity http) throws Exception {
C’est bien ça d’avoir différents profiles. Faudrait faire un ticket pour une config de prod (même minim) avant de merge.

2024-12-26 15:48 UTC, LeNelSoN commented on src/main/java/com/edj/teamoop/model/Project.java
> +        this.startDate = LocalDate.now();
Si, tu passe des paramètres dans le constructeur pourquoi tu met des valeurs fixes ?

2024-12-26 15:48 UTC, LeNelSoN commented on src/main/java/com/edj/teamoop/model/Project.java
> +        this(name, description, LocalDate.now(), LocalDate.now(), true);
Tu injecte les données dans le constructeur. Vue l’utilisation du constructeur précédemment, le mieux et décrire des surcharges de méthode de constructeur, s’il en faut plusieurs.

2024-12-26 15:48 UTC, LeNelSoN commented on src/main/java/com/edj/teamoop/model/Project.java
> +    public Long getId() {
Si tu importe lombok, tu peux l’utiliser pour les getters et les setters. Plutôt que d’écrire plein de code.

2025-01-05 14:03 UTC, allanserre commented on src/main/java/com/edj/teamoop/model/Project.java
> +    public Long getId() {
C'est de l'auto génération heureusement, je vais regarder pour lombok

2025-01-06 23:03 UTC, LeNelSoN requested changes

2025-01-06 23:03 UTC, LeNelSoN commented on src/main/java/com/edj/teamoop/service/ProjectService.java
> +    public Optional<Project> getProjectById(Long id) {
T'as créé une méthode `getProjectById` mais tu renvoie un Optional, tu devrais résoudre le Optional et renvoyer l'objet ou déclancher une exception (Une personnalisé serait le mieux), s'il est absent. Car la gestion des exceptions est centralisé dans un handler.

2025-01-06 23:03 UTC, LeNelSoN commented on mvnw.cmd
> +    <# : batch portion
?

2025-01-06 23:03 UTC, LeNelSoN commented on src/test/java/com/edj/teamoop/service/ProjectServiceTest.java
> +        projectService.createProject("Project 1", "Description 1");
Trop de couplage, si tu utilise une methode de service pour préparer tes tests. Faut faire un `new Project` ici. En plus pour la couverture de code `createProject` doit etre testé

2025-01-06 23:03 UTC, LeNelSoN commented on src/main/java/com/edj/teamoop/model/Project.java
> +    public Project(String name, String description,  LocalDate startDate,  LocalDate endDate, boolean active) {
On a besoin de ce constructeur ? alors qu'on a deja le `@NoArgsContructor`

2025-01-06 23:03 UTC, LeNelSoN commented on src/main/java/com/edj/teamoop/model/Project.java
> +        this(name, description, LocalDate.now(), LocalDate.now(), true);
C'est de la logique métier, si y'a besoin ca doit etre dans la couche service.

2025-01-06 23:12 UTC, LeNelSoN requested changes

2025-01-06 23:12 UTC, LeNelSoN commented on src/main/java/com/edj/teamoop/service/ProjectService.java
> +        Project p = new Project(name, description);
Les timestamps du coup doivent apparaitrent ici, ca sera plus facile à maintenir que dans le model.

2025-01-06 23:15 UTC, LeNelSoN commented
Faudra décrire la PR pour expliquer ce que tu as fais, parce que y'a plein de choses différentes qui ne sont pas en lien avec l'intégration de la BDD.

2025-01-06 23:38 UTC, allanserre commented on src/main/java/com/edj/teamoop/model/Project.java
> +    public Project(String name, String description,  LocalDate startDate,  LocalDate endDate, boolean active) {
Tu voudrais que j'utilise le @no arg puis que je set les valeurs une à une ensuite pour construire l'objet ?

2025-01-07 10:17 UTC, LeNelSoN commented on src/main/java/com/edj/teamoop/service/ProjectService.java
> +            throw new IllegalArgumentException("Le projet avec  l'id " + id + " n'existe pas.");
On va faire des customs exceptions pour centraliser la gestion

2025-01-07 10:28 UTC, LeNelSoN commented on src/test/java/com/edj/teamoop/service/ProjectServiceTest.java
> +        projectRepository.save(p2);
La BDD H2 est utilisé pour les tests d'intégration pas les tests unitaires. Sur un test unitaire on verifie le comportement d'une unité de code. Ici faut mocker la BDD.à

2025-01-07 10:56 UTC, LeNelSoN approved these changes

2025-01-07 10:57 UTC, allanserre commented on src/main/java/com/edj/teamoop/service/ProjectService.java
> +            throw new IllegalArgumentException("Le projet avec  l'id " + id + " n'existe pas.");
Ticket ajouté

2025-01-07 10:58 UTC, allanserre commented on src/test/java/com/edj/teamoop/service/ProjectServiceTest.java
> +        projectRepository.save(p2);
Déplacement des tests dans une autre PR

2025-01-07 10:58 UTC, allanserre commented on src/main/java/com/edj/teamoop/service/ProjectService.java
> +        Project p = new Project(name, description);
Suppression de la méthode

2025-01-07 10:59 UTC, merged